file:
  directory: /home/download/auth

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka
    instance:
      instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

server:
  port: 0
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.0.144/db_even_first_5
    username: even_first_5
    password: gggg
  jpa:
    hibernate:
      ddl-auto: none

