constants:
  file:
    upload-directory: /home/download

eureka:
  client:
    enabled: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
    loadbalancer:
      enabled: true

  datasource:
    url: jdbc:log4jdbc:mariadb://user-db.greengram-db.svc.cluster.local/greengram_user
    username: root
    password: green502

  jpa:
    hibernate:
      ddl-auto: none


