constants:
  file:
    upload-directory: /home/download

eureka:
  client:
    enabled: false

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
      reload:
        enabled: true
        strategy: refresh
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.0.74/greengram_user
    username: root
    password: green502

  jpa:
    hibernate:
      ddl-auto: update


