constants:
  file:
    upload-directory: /home/download
  jwt:
    refresh-token-cookie-path: /greengram-api/api/user/reissue

eureka:
  client:
    enabled: false

server:
  port: 8080
  shutdown: graceful
  # 우아한 종료(graceful shutdown) Default값
  #
  #프로세스가 SIGTERM 신호를 받고 종료 절차 시작.
  #새 요청은 받지 않음.
  #진행 중이던 요청을 끝까지 처리.
  #DB 연결, 메시지 큐, 쓰레드 풀 같은 리소스를 정리(close).
  #그 후 안전하게 프로세스 종료.

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
      reload:
        enabled: true
        strategy: refresh
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.0.74/greengram_user
    username: root
    password: green502
  jpa:
    hibernate:
      ddl-auto: update

  lifecycle:
    timeout-per-shutdown-phase: 30s  # Pod 종료 대기 시간
